name: Guestbook

on:
  issues:
    types: [opened, closed, reopened, deleted, edited]
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update_guestbook:
    name: Update the guestbook
    runs-on: ubuntu-latest

    steps:
      - uses: Renato66/auto-label@v2 # or v2.4.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          default-labels: '["guestbook_entry"]'
      - uses: actions/checkout@v4
      - name: Update guestbook with latest guest post entries
        uses: nfhipona/guestbook-workflow@main
        with:
          target_branch: 'main'
          section_identifier: 'guestbook-section'